### ISSUE TITLE
Review extensions methods

### ISSUE THREAD

**Issue by alercunha** [zbra-dev/maybe#11]
Let's put together a list of suggestions to improve the overall API. Certain methods could have been more carefully thought.

OrGetAlternative: Seems to do exactly what OrGet already does except for adding an option that returns a Maybe<T> instead of T
Compact => Name is a bit confusing, maybe consider removing this or finding better name

**Comment by spliner** [comment]
Closing this issue. `OrGetAlternative` and `Compact` have already been renamed and we're sticking with `SelectMany`.
